version: "3.9" 
services:
  sql.data:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=1qaz@WSX
  web_api:
    image: web_api
    ports:
      - "5000:80"
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - sql.data
  